**This notebook is an exercise in the [Advanced SQL](https://www.kaggle.com/learn/advanced-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/alexisbcook/joins-and-unions).**

---

# Introduction

Here, you'll use different types of SQL **JOINs** to answer questions about the [Stack Overflow](https://www.kaggle.com/stackoverflow/stackoverflow) dataset.

Before you get started, run the following cell to set everything up.

In [1]:
# Set up feedback system
from learntools.core import binder
binder.bind(globals())
from learntools.sql_advanced.ex1 import *
print("Setup Complete")

Using Kaggle's public dataset BigQuery integration.

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/client.py:440: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  "Cannot create BigQuery Storage client, the dependency "

Setup Complete

The code cell below fetches the `posts_questions` table from the `stackoverflow` dataset.  We also preview the first five rows of the table.

In [2]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "stackoverflow" dataset
dataset_ref = client.dataset("stackoverflow", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

# Construct a reference to the "posts_questions" table
table_ref = dataset_ref.table("posts_questions")

# API request - fetch the table
table = client.get_table(table_ref)

# Preview the first five lines of the table
client.list_rows(table, max_results=5).to_dataframe()

Using Kaggle's public dataset BigQuery integration.

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:19: UserWarning: Cannot use bqstorage_client if max_results is set, reverting to fetching data with the tabledata.list endpoint.

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,320268,Html.ActionLink doesnâ€™t render # properly,<p>When using Html.ActionLink passing a string...,NaN,0,0,NaT,2008-11-26 10:42:37.477000+00:00,0,2009-02-06 20:13:54.370000+00:00,NaT,None,NaN,Paulo,NaN,None,1,0,asp.net-mvc,390
1,324003,Primitive recursion,<p>how will i define the function 'simplify' ...,NaN,0,0,NaT,2008-11-27 15:12:37.497000+00:00,0,2012-09-25 19:54:40.597000+00:00,2012-09-25 19:54:40.597000+00:00,Marcin,1288.0,None,41000.0,None,1,0,haskell|lambda|functional-programming|lambda-c...,497
2,390605,While vs. Do While,<p>I've seen both the blocks of code in use se...,390608.0,0,0,NaT,2008-12-24 01:49:54.230000+00:00,2,2008-12-24 03:08:55.897000+00:00,NaT,None,NaN,Unkwntech,115.0,None,1,0,language-agnostic|loops,11262
3,413246,Protect ASP.NET Source code,<p>Im currently doing some research in how to ...,NaN,0,0,NaT,2009-01-05 14:23:51.040000+00:00,0,2009-03-24 21:30:22.370000+00:00,2009-01-05 14:42:28.257000+00:00,Tom Anderson,13502.0,Velnias,NaN,None,1,0,asp.net|deployment|obfuscation,4823
4,454921,"Difference between ""int[] myArray"" and ""int my...",<blockquote>\n <p><strong>Possible Duplicate:...,454928.0,0,0,NaT,2009-01-18 10:22:52.177000+00:00,0,2009-01-18 10:30:50.930000+00:00,2017-05-23 11:49:26.567000+00:00,None,-1.0,Evan Fosmark,49701.0,None,1,0,java|arrays,798

We also take a look at the `posts_answers` table.

In [3]:
# Construct a reference to the "posts_answers" table
table_ref = dataset_ref.table("posts_answers")

# API request - fetch the table
table = client.get_table(table_ref)

# Preview the first five lines of the table
client.list_rows(table, max_results=50).to_dataframe()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:8: UserWarning: Cannot use bqstorage_client if max_results is set, reverting to fetching data with the tabledata.list endpoint.

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,18,None,<p>For a table like this:</p>\n\n<pre><code>CR...,None,None,2,NaT,2008-08-01 05:12:44.193000+00:00,None,2016-06-02 05:56:26.060000+00:00,2016-06-02 05:56:26.060000+00:00,Jeff Atwood,126039,phpguy,NaN,17,2,59,None,None
1,165,None,"<p>You can use a <a href=""http://sharpdevelop....",None,None,0,NaT,2008-08-01 18:04:25.023000+00:00,None,2019-04-06 14:03:51.080000+00:00,2019-04-06 14:03:51.080000+00:00,None,1721793,user2189331,NaN,145,2,10,None,None
2,1028,None,<p>The VB code looks something like this:</p>\...,None,None,0,NaT,2008-08-04 04:58:40.300000+00:00,None,2013-02-07 13:22:14.680000+00:00,2013-02-07 13:22:14.680000+00:00,None,395659,user2189331,NaN,947,2,8,None,None
3,1073,None,<p>My first choice would be a dedicated heap t...,None,None,0,NaT,2008-08-04 07:51:02.997000+00:00,None,2015-09-01 17:32:32.120000+00:00,2015-09-01 17:32:32.120000+00:00,None,45459,user2189331,NaN,1069,2,29,None,None
4,1260,None,<p>I found the answer. all you have to do is a...,None,None,0,NaT,2008-08-04 14:06:02.863000+00:00,None,2016-12-20 08:38:48.867000+00:00,2016-12-20 08:38:48.867000+00:00,None,1221571,Jin,NaN,1229,2,1,None,None
5,2216,None,"<p>Thxm, Mc! <a href=""http://asm.objectweb.org...",None,None,0,NaT,2008-08-05 12:50:59.020000+00:00,None,2016-10-13 12:50:44.040000+00:00,2016-10-13 12:50:44.040000+00:00,None,1571180,bill,NaN,2092,2,4,None,None
6,2498,None,<p>The two self-balancing <code>BST</code>s I'...,None,None,0,NaT,2008-08-05 15:50:05.120000+00:00,None,2013-02-07 14:40:26.280000+00:00,2013-02-07 14:40:26.280000+00:00,None,395659,user316,NaN,2481,2,0,None,None
7,2977,None,"<p>I would look at <a href=""http://www.google....",None,None,0,NaT,2008-08-06 00:16:25.020000+00:00,None,2008-08-06 16:20:17.193000+00:00,2008-08-06 16:20:17.193000+00:00,Justin Standard,92,user2189331,NaN,2968,2,7,None,None
8,6206,None,<p>For a 3x3 system of linear equations I gues...,None,None,0,NaT,2008-08-08 17:59:27.907000+00:00,None,2016-12-20 05:58:05.240000+00:00,2016-12-20 05:58:05.240000+00:00,None,1997093,Pall Melsted,NaN,769,2,7,None,None
9,6620,None,<p><strong>Pros of config file:</strong> </p>...,None,None,4,NaT,2008-08-09 04:51:59.773000+00:00,None,2011-02-25 13:13:38.733000+00:00,2011-02-25 13:13:38.733000+00:00,None,8418,user316,NaN,6607,2,44,None,None
10,6700,None,<h2>Updated answer</h2>\n<p><strong>Here's an ...,None,None,16,NaT,2008-08-09 08:31:04.577000+00:00,None,2021-11-25 12:13:16.077000+00:00,2021-11-25 12:13:16.077000+00:00,user985399,123671,James Coglan,NaN,5223,2,3169,None,None
11,7587,None,<p>How about using the new Workflow components...,None,None,0,NaT,2008-08-11 07:33:18.730000+00:00,None,2016-11-20 00:25:16.067000+00:00,2016-11-20 00:25:16.067000+00:00,None,6392939,lone wolf,NaN,6210,2,0,None,None
12,7842,None,<p>You can do this in two lines in python with...,None,None,1,NaT,2008-08-11 14:47:31.227000+00:00,None,2020-07-27 01:15:48.273000+00:00,2020-07-27 01:15:48.273000+00:00,None,6800539,Pall Melsted,NaN,826,2,2,None,None
13,8661,None,"<p>Another thing to consider: in debug mode, t...",None,None,0,NaT,2008-08-12 10:48:18.663000+00:00,None,2012-09-07 22:59:47.557000+00:00,2012-09-07 22:59:47.557000+00:00,None,450827,HS,NaN,8612,2,0,None,None
14,10287,None,<p>The only reason why I wouldn't use the <cod...,None,None,7,NaT,2008-08-13 19:32:25.253000+00:00,None,2018-07-12 14:55:27.010000+00:00,2018-07-12 14:55:27.010000+00:00,None,6916677,user1228,NaN,10274,2,17,None,None
15,10838,None,<p>If you're using Sybase 12.5 or earlier then...,None,None,0,NaT,2008-08-14 09:27:30.793000+00:00,None,2014-03-23 20:23:24.110000+00:00,2014-03-23 20:23:24.110000+00:00,None,267702,user3378,NaN,6369,2,4,None,None
16,11122,None,"<p>For AzMan with ASP.NET, turn on impersonati...",None,None,1,NaT,2008-08-14 14:34:30.030000+00:00,None,2014-12-13 07:35:42.273000+00:00,2014-12-13 07:35:42.273000+00:00,None,1810429,littlegeek,NaN,10810,2,2,None,None
17,11775,None,"<p>The <a href=""http://msdn.microsoft.com/en-u...",None,None,1,NaT,2008-08-14 23:25:12.967000+00:00,None,2016-01-17 12:54:56.970000+00:00,2016-01-17 12:54:56.970000+00:00,None,490018,user1010,NaN,11767,2,62,None,None
18,12143,None,<p>I dropped the live database and deleted it....,None,None,1,NaT,2008-08-15 11:15:45.483000+00:00,None,2008-11-09 17:24:30.207000+00:00,2008-11-09 17:24:30.207000+00:00,splattne,6461,littlegeek,NaN,12141,2,1,None,None
19,12241,None,"<p>Look, there's no easy way to do this. I'm ...",None,None,8,NaT,2008-08-15 13:29:01.523000+00:00,None,2020-10-27 06:26:01.603000+00:00,2020-10-27 06:26:01.603000+00:00,Hamish Smith,1402846,user1228,NaN,12159,2,270,None,None
20,13097,None,"<p>You need to use a layer 4 <a href=""http://e...",None,None,0,NaT,2008-08-16 11:38:55.397000+00:00,None,2013-12-02 14:04:21.527000+00:00,2013-12-02 14:04:21.527000+00:00,None,781754,user1010,NaN,4335,2,10,None,None
21,13467,None,<p>Here are two articles that are very helpful...,None,None,0,NaT,2008-08-17 01:47:59.377000+00:00,None,2012-08-11 15:42:57.723000+00:00,2012-08-11 15:42:57.723000+00:00,None,1477076,roger pence,NaN,13460,2,3,None,None
22,13690,None,<p>You can reduce the server-side load by perf...,None,None,0,2009-09-04 13:15:59.820000+00:00,2008-08-17 15:56:26.810000+00:00,None,2018-09-27 09:13:12.363000+00:00,2018-09-27 09:13:12.363000+00:00,None,5407188,J,NaN,11,2,11,None,None
23,14859,None,"<p>Make sure the <a href=""http://msdn.microsof...",None,None,0,NaT,2008-08-18 16:21:39.380000+00:00,None,2013-02-22 21:34:39.720000+00:00,2013-02-22 21:34:39.720000+00:00,None,560648,user2189331,NaN,14843,2,14,None,None
24,15038,None,<p>I've seen various people with this problem ...,None,None,0,NaT,2008-08-18 18:26:14.043000+00:00,None,2014-09-23 08:20:04.870000+00:00,2014-09-23 08:20:04.870000+00:00,None,3212782,user2189331,NaN,14963,2,2,None,None
25,15096,None,<p>I would strongly recommend against this.</p...,None,None,0,NaT,2008-08-18 19:09:12.880000+00:00,None,2012-08-11 16:10:15.220000+00:00,2012-08-11 16:10:15.220000+00:00,None,1477076,user2189331,NaN,14674,2,0,None,None
26,15269,None,"<p>I still do it the old way, by defining a ma...",None,None,6,NaT,2008-08-18 21:42:09.857000+00:00,None,2016-04-09 23:06:06.310000+00:00,2016-04-09 23:06:06.310000+00:00,None,1162609,user2189331,NaN,15240,2,24,None,None
27,16456,None,<blockquote>\n <p>Note that a responsible web...,None,None,0,NaT,2008-08-19 15:56:26.043000+00:00,None,2014-05-03 17:56:12.340000+00:00,2014-05-03 17:56:12.340000+00:00,CodingTheWheel,707111,user2189331,NaN,16233,2,2,None,None
28,18672,None,<p>Tail is the best answer so far.</p>\n\n<p>I...,None,None,1,NaT,2008-08-20 19:50:19.620000+00:00,None,2019-11-27 04:10:39.327000+00:00,2019-11-27 04:10:39.327000+00:00,None,10854998,Adam,NaN,18632,2,8,None,None
29,18841,None,"<p>Use <a href=""https://github.com/jgm/pandoc""...",None,None,4,NaT,2008-08-20 21:05:03.713000+00:00,None,2017-05-21 01:29:30.740000+00:00,2017-05-21 01:29:30.740000+00:00,None,15168,Doe,NaN,18754,2,66,None,None
30,19726,None,<p>there is also an argument for separating th...,None,None,0,NaT,2008-08-21 12:31:34.190000+00:00,None,2015-09-22 04:56:12.220000+00:00,2015-09-22 04:56:12.220000+00:00,None,1540450,Richard,NaN,12982,2,1,None,None
31,20153,None,<p>Path.GetTempFileName and Path.GetTempPath. ...,None,None,0,NaT,2008-08-21 14:53:04.473000+00:00,None,2014-11-03 09:21:50.857000+00:00,2014-11-03 09:21:50.857000+00:00,Will,2213647,user1228,NaN,20146,2,9,None,None
32,23335,None,<p>I believe that procedural/functional/object...,None,None,0,NaT,2008-08-22 19:57:34.877000+00:00,None,2015-04-10 03:07:14.550000+00:00,2015-04-10 03:07:14.550000+00:00,Harleqin,541136,Lam Luu,NaN,23277,2,26,None,None
33,26164,None,<p>Coding Horror has a great post about <a hre...,None,None,0,2008-09-23 06:50:43.100000+00:00,2008-08-25 14:52:48.733000+00:00,None,2018-04-11 16:59:29.907000+00:00,2018-04-11 16:59:29.907000+00:00,None,2093371,user290,NaN,2658,2,1,None,None
34,27943,None,"<p>This <a href=""http://www.movable-type.co.uk...",None,None,25,NaT,2008-08-26 12:55:53.030000+00:00,None,2014-07-31 01:25:14.147000+00:00,2014-07-31 01:25:14.147000+00:00,Adam Davis,3204551,user1921,NaN,27928,2,1319,None,None
35,28240,None,"<p>Create an intermediate shim type ""<code>Rec...",None,None,0,NaT,2008-08-26 14:44:41.257000+00:00,None,2015-10-08 07:40:05.173000+00:00,2015-10-08 07:40:05.173000+00:00,None,67579,user2189331,NaN,28212,2,4,None,None
36,28837,None,"<p>I've recently set up <a href=""http://www.ca...",None,None,0,NaT,2008-08-26 18:53:01.267000+00:00,None,2017-09-25 18:51:04.010000+00:00,2017-09-25 18:51:04.010000+00:00,None,6761181,Ryan Anthony,NaN,28768,2,1,None,None
37,29509,None,<p>I use a ternary in a printf like this:</p>\...,None,None,1,NaT,2008-08-27 04:19:16.540000+00:00,None,2015-11-16 14:28:18.800000+00:00,2015-11-16 14:28:18.800000+00:00,None,1084,Rodney,NaN,29383,2,3,None,None
38,31191,None,"<p>For what it's worth, caching is DIRT SIMPLE...",None,None,2,NaT,2008-08-27 20:32:06.683000+00:00,None,2016-01-15 15:32:42.777000+00:00,2016-01-15 15:32:42.777000+00:00,None,4932070,Shane,NaN,24675,2,6,None,None
39,32329,None,"<p><a href=""https://innig.net/software/ruby/cl...",None,None,1,NaT,2008-08-28 13:50:12.320000+00:00,None,2018-08-08 06:19:51.517000+00:00,2018-08-08 06:19:51.517000+00:00,None,337446,codebrulee,NaN,626,2,6,None,None
40,32857,None,"<p>this might be way more than you need, but t...",None,None,0,NaT,2008-08-28 17:23:22.073000+00:00,None,2013-07-12 21:52:12.500000+00:00,2013-07-12 21:52:12.500000+00:00,None,1011749,mark streatfield,NaN,32044,2,20,None,None
41,33035,None,<p>They are very similar. With Objective-C 2.0...,None,None,2,NaT,2008-08-28 18:37:27.543000+00:00,None,2015-02-10 14:49:44.207000+00:00,2015-02-10 14:49:44.207000+00:00,Jeff Atwood,3353294,RogueStrider,NaN,32986,2,2,None,None
42,33707,None,"<p>GPS, the Global Positioning System run by t...",None,None,1,NaT,2008-08-29 00:36:44.687000+00:00,None,2016-02-27 15:12:04.087000+00:00,2016-02-27 15:12:04.087000+00:00,Adam Davis,229044,Adam Davis,NaN,33637,2,56,None,None
43,33724,None,<p>Without knowing the return value of <code>p...,None,None,0,NaT,2008-08-29 00:46:44.020000+00:00,None,2009-11-21 06:38:59.240000+00:00,2009-11-21 06:38:59.240000+00:00,None,56338,Rodney,NaN,33199,2,3,None,None
44,33741,None,<p>I would take a look at proven APIs:</p>\n\n...,None,None,0,NaT,2008-08-29 01:12:11.557000+00:00,None,2013-03-21 15:51:31.963000+00:00,2013-03-21 15:51:31.963000+00:00,None,2025,user2189331,NaN,33728,2,7,None,None
45,33757,None,<p>I use this rule of thumb:</p>\n\n<ol>\n<li>...,None,None,12,NaT,2008-08-29 01:28:13.203000+00:00,None,2011-08-29 13:14:48.447000+00:00,2011-08-29 13:14:48.447000+00:00,None,161336,user1921,NaN,33746,2,151,None,None
46,33930,None,"<p>In <strong>traditional recursion</strong>, ...",None,None,9,NaT,2008-08-29 03:57:07.590000+00:00,None,2018-07-30 03:41:50.897000+00:00,2018-07-30 03:41:50.897000+00:00,None,1966418,user316,NaN,33923,2,803,None,None
47,34472,None,<p>To check if it has a particular method:</p>...,None,None,1,NaT,2008-08-29 15:40:05.017000+00:00,None,2012-07-30 04:12:14.040000+00:00,2012-07-30 04:12:14.040000+00:00,None,1288,figg,NaN,34439,2,34,None,None
48,37042,None,<p><code>%</code> is replaced with the current...,None,None,7,NaT,2008-08-31 19:23:48.347000+00:00,None,2018-12-11 23:21:40.697000+00:00,2018-12-11 23:21:40.697000+00:00,None,1681480,user3850,NaN,1005,2,308,None,None
49,37736,None,"<h1>Recursive Prolog</h1>\n\n<pre><code>fac(0,...",None,None,0,2008-09-19 07:14:59.840000+00:00,2008-09-01 11:00:07.783000+00:00,None,2008-10-14 15:18:09.453000+00:00,2008-10-14 15:18:09.453000+00:00,Brad Gilbert,1337,tef,NaN,23930,2,8,None,None

You will work with both of these tables to answer the questions below.

# Exercises

### 1) How long does it take for questions to receive answers?

You're interested in exploring the data to have a better understanding of how long it generally takes for questions to receive answers.  Armed with this knowledge, you plan to use this information to better design the order in which questions are presented to Stack Overflow users.

With this goal in mind, you write the query below, which focuses on questions asked in January 2018.  It returns a table with two columns:
- `q_id` - the ID of the question
- `time_to_answer` - how long it took (in seconds) for the question to receive an answer

Run the query below (without changes), and take a look at the output.

In [4]:
first_query = """
              SELECT q.id AS q_id,
                  MIN(TIMESTAMP_DIFF(a.creation_date, q.creation_date, SECOND)) as time_to_answer
              FROM `bigquery-public-data.stackoverflow.posts_questions` AS q
                  INNER JOIN `bigquery-public-data.stackoverflow.posts_answers` AS a
              ON q.id = a.parent_id
              WHERE q.creation_date >= '2018-01-01' and q.creation_date < '2018-02-01'
              GROUP BY q_id
              ORDER BY time_to_answer
              """

first_result = client.query(first_query).result().to_dataframe()
print("Percentage of answered questions: %s%%" % \
      (sum(first_result["time_to_answer"].notnull()) / len(first_result) * 100))
print("Number of questions:", len(first_result))
first_result.head()

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/client.py:440: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  "Cannot create BigQuery Storage client, the dependency "

Percentage of answered questions: 100.0%
Number of questions: 134719

       q_id  time_to_answer
0  48382183      -132444692
1  48174391               0
2  48375126               0
3  48092100               0
4  48102324               0

You're surprised at the results and strongly suspect that something is wrong with your query.  In particular,
- According to the query, 100% of the questions from January 2018 received an answer.  But, you know that ~80% of the questions on the site usually receive an answer.
- The total number of questions is surprisingly low.  You expected to see at least 150,000 questions represented in the table.

Given these observations, you think that the type of **JOIN** you have chosen has inadvertently excluded unanswered questions.  Using the code cell below, can you figure out what type of **JOIN** to use to fix the problem so that the table includes unanswered questions?

**Note**: You need only amend the type of **JOIN** (i.e., **INNER**, **LEFT**, **RIGHT**, or **FULL**) to answer the question successfully.

In [5]:
# Your code here
correct_query = """
              SELECT q.id AS q_id,
                  MIN(TIMESTAMP_DIFF(a.creation_date, q.creation_date, SECOND)) as time_to_answer
              FROM `bigquery-public-data.stackoverflow.posts_questions` AS q
                  LEFT JOIN `bigquery-public-data.stackoverflow.posts_answers` AS a
              ON q.id = a.parent_id
              WHERE q.creation_date >= '2018-01-01' and q.creation_date < '2018-02-01'
              GROUP BY q_id
              ORDER BY time_to_answer
                """

# Check your answer
q_1.check()

# Run the query, and return a pandas DataFrame
correct_result = client.query(correct_query).result().to_dataframe()
print("Percentage of answered questions: %s%%" % \
      (sum(correct_result["time_to_answer"].notnull()) / len(correct_result) * 100))
print("Number of questions:", len(correct_result))

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/client.py:440: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  "Cannot create BigQuery Storage client, the dependency "

       q_id  time_to_answer
0  48496152             NaN
1  48186557             NaN
2  48062767             NaN
3  48235183             NaN
4  48401659             NaN

Correct

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/client.py:440: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  "Cannot create BigQuery Storage client, the dependency "

Percentage of answered questions: 83.3368387192557%
Number of questions: 161656

In [6]:
# Lines below will give you a hint or solution code
q_1.hint()
q_1.solution()

Hint: Is the `posts_questions` table the **LEFT** or **RIGHT** table?  You want to keep all of the rows from this table, regardless of whether or not there is a match in the `posts_answers` table.

Solution:
```python

correct_query = """
                SELECT q.id AS q_id,
                    MIN(TIMESTAMP_DIFF(a.creation_date, q.creation_date, SECOND)) as time_to_answer
                FROM `bigquery-public-data.stackoverflow.posts_questions` AS q
                    LEFT JOIN `bigquery-public-data.stackoverflow.posts_answers` AS a
                ON q.id = a.parent_id
                WHERE q.creation_date >= '2018-01-01' and q.creation_date < '2018-02-01'
                GROUP BY q_id
                ORDER BY time_to_answer
                """

```

### 2) Initial questions and answers, Part 1

You're interested in understanding the initial experiences that users typically have with the Stack Overflow website.  Is it more common for users to first ask questions or provide answers?  After signing up, how long does it take for users to first interact with the website?  To explore this further, you draft the (partial) query in the code cell below.

The query returns a table with three columns:
- `owner_user_id` - the user ID
- `q_creation_date` - the first time the user asked a question 
- `a_creation_date` - the first time the user contributed an answer 

You want to keep track of users who have asked questions, but have yet to provide answers.  And, your table should also include users who have answered questions, but have yet to pose their own questions.  

With this in mind, please fill in the appropriate **JOIN** (i.e., **INNER**, **LEFT**, **RIGHT**, or **FULL**) to return the correct information.  

**Note**: You need only fill in the appropriate **JOIN**.  All other parts of the query should be left as-is.  (You also don't need to write any additional code to run the query, since the `check()` method will take care of this for you.)

To avoid returning too much data, we'll restrict our attention to questions and answers posed in January 2019.  We'll amend the timeframe in Part 2 of this question to be more realistic!

In [7]:
# Your code here
q_and_a_query = """
                SELECT q.owner_user_id AS owner_user_id,
                    MIN(q.creation_date) AS q_creation_date,
                    MIN(a.creation_date) AS a_creation_date
                FROM `bigquery-public-data.stackoverflow.posts_questions` AS q
                    FULL JOIN `bigquery-public-data.stackoverflow.posts_answers` AS a
                ON q.owner_user_id = a.owner_user_id 
                WHERE q.creation_date >= '2019-01-01' AND q.creation_date < '2019-02-01' 
                    AND a.creation_date >= '2019-01-01' AND a.creation_date < '2019-02-01'
                GROUP BY owner_user_id
                """

# Check your answer
q_2.check()

,owner_user_id,q_creation_date,a_creation_date
0,802365,2019-01-22 08:53:29.047000+00:00,2019-01-08 11:35:38.670000+00:00
1,10946476,2019-01-22 22:35:42.887000+00:00,2019-01-23 00:25:41.097000+00:00
2,265791,2019-01-25 00:25:11.883000+00:00,2019-01-30 15:54:41.510000+00:00
3,6748184,2019-01-29 08:04:20.633000+00:00,2019-01-29 08:04:20.633000+00:00
4,5705247,2019-01-05 07:33:26.467000+00:00,2019-01-06 08:30:18.300000+00:00

Correct

In [8]:
# Lines below will give you a hint or solution code
q_2.hint()
q_2.solution()

Hint: Which type of JOIN always returns all rows from both tables?

Solution:
```python

q_and_a_query = """
                SELECT q.owner_user_id AS owner_user_id,
                    MIN(q.creation_date) AS q_creation_date,
                    MIN(a.creation_date) AS a_creation_date
                FROM `bigquery-public-data.stackoverflow.posts_questions` AS q
                    FULL JOIN `bigquery-public-data.stackoverflow.posts_answers` AS a
                ON q.owner_user_id = a.owner_user_id
                WHERE q.creation_date >= '2019-01-01' AND q.creation_date < '2019-02-01'
                    AND a.creation_date >= '2019-01-01' AND a.creation_date < '2019-02-01'
                GROUP BY owner_user_id
                """

```

### 3) Initial questions and answers, Part 2

Now you'll address a more realistic (and complex!) scenario.  To answer this question, you'll need to pull information from *three* different tables!  This syntax very similar to the case when we have to join only two tables.  For instance, consider the three tables below.

![three tables](https://i.imgur.com/OyhYtD1.png)

We can use two different **JOINs** to link together information from all three tables, in a single query.

![double join](https://i.imgur.com/G6buS7P.png)

With this in mind, say you're interested in understanding users who joined the site in January 2019.  You want to track their activity on the site: when did they post their first questions and answers, if ever?

Write a query that returns the following columns:
- `id` - the IDs of all users who created Stack Overflow accounts in January 2019 (January 1, 2019, to January 31, 2019, inclusive)
- `q_creation_date` - the first time the user posted a question on the site; if the user has never posted a question, the value should be null
- `a_creation_date` - the first time the user posted a question on the site; if the user has never posted a question, the value should be null

Note that questions and answers posted after January 31, 2019, should still be included in the results.  And, all users who joined the site in January 2019 should be included (even if they have never posted a question or provided an answer).

The query from the previous question should be a nice starting point to answering this question!  You'll need to use the `posts_answers` and `posts_questions` tables.  You'll also need to use the `users` table from the Stack Overflow dataset.  The relevant columns from the `users` table are `id` (the ID of each user) and `creation_date` (when the user joined the Stack Overflow site, in DATETIME format).

In [9]:
# Your code here
three_tables_query = """
                        SELECT u.id as id,
                            MIN(q.creation_date) AS q_creation_date,
                            MIN(a.creation_date) AS a_creation_date
                        FROM `bigquery-public-data.stackoverflow.users` AS u
                            FULL JOIN `bigquery-public-data.stackoverflow.posts_answers` AS a
                                ON a.owner_user_id = u.id
                            FULL JOIN `bigquery-public-data.stackoverflow.posts_questions` AS q 
                                ON q.owner_user_id = u.id             
                        WHERE u.creation_date >= '2019-01-01' AND u.creation_date < '2019-02-01' 
                        GROUP BY id
                    """

# Check your answer
q_3.check()

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/client.py:440: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  "Cannot create BigQuery Storage client, the dependency "

         id                  q_creation_date                  a_creation_date
0  10968515                              NaT 2021-04-13 22:21:32.863000+00:00
1  10893746 2019-01-10 07:08:02.980000+00:00                              NaT
2  10903455 2019-01-14 16:19:37.283000+00:00                              NaT
3  10984058                              NaT                              NaT
4  10944112                              NaT                              NaT

Correct

In [10]:
# Lines below will give you a hint or solution code
q_3.hint()
#q_3.solution()

Hint:
Here's a partially completed query.  You need only fill in the appropriate JOINs!
```
three_tables_query = """
                     SELECT u.id AS id,
                         MIN(q.creation_date) AS q_creation_date,
                         MIN(a.creation_date) AS a_creation_date
                     FROM `bigquery-public-data.stackoverflow.users` AS u
                         ____ `bigquery-public-data.stackoverflow.posts_answers` AS a
                             ON u.id = a.owner_user_id
                         ____ `bigquery-public-data.stackoverflow.posts_questions` AS q
                             ON q.owner_user_id = u.id
                     WHERE u.creation_date >= '2019-01-01' and u.creation_date < '2019-02-01'
                     GROUP BY id
                    """
```

### 4) How many distinct users posted on January 1, 2019?

In the code cell below, write a query that returns a table with a single column:
- `owner_user_id` - the IDs of all users who posted at least one question or answer on January 1, 2019.  Each user ID should appear at most once.

In the `posts_questions` (and `posts_answers`) tables, you can get the ID of the original poster from the `owner_user_id` column.  Likewise, the date of the original posting can be found in the `creation_date` column.  

In order for your answer to be marked correct, your query must use a **UNION**.

In [11]:
# Your code here
all_users_query = """
                    SELECT q.owner_user_id
                    FROM `bigquery-public-data.stackoverflow.posts_questions` AS q 
                    WHERE EXTRACT(DATE FROM q.creation_date) = '2019-01-01'
                    
                    UNION DISTINCT
                    
                    SELECT a.owner_user_id
                    FROM `bigquery-public-data.stackoverflow.posts_answers` AS a 
                    WHERE EXTRACT(DATE FROM a.creation_date) = '2019-01-01'
                    
                  """

# Check your answer
q_4.check()

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/client.py:440: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  "Cannot create BigQuery Storage client, the dependency "

   owner_user_id
0     10849497.0
1     10640995.0
2     10853546.0
3     10855367.0
4      1621517.0

Correct

In [12]:
# Lines below will give you a hint or solution code
q_4.hint()
q_4.solution()

Hint: Begin by writing two separate queries: one to get the user IDs corresponding to questions, and another corresponding to answers.  Then, take the union of the two columns.

Solution:
```python

all_users_query = """
                  SELECT q.owner_user_id
                  FROM `bigquery-public-data.stackoverflow.posts_questions` AS q
                  WHERE EXTRACT(DATE FROM q.creation_date) = '2019-01-01'
                  UNION DISTINCT
                  SELECT a.owner_user_id
                  FROM `bigquery-public-data.stackoverflow.posts_answers` AS a
                  WHERE EXTRACT(DATE FROM a.creation_date) = '2019-01-01'
                  """

```

# Keep going

Learn how to use **[analytic functions](https://www.kaggle.com/alexisbcook/analytic-functions)** to perform complex calculations with minimal SQL code.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/advanced-sql/discussion) to chat with other learners.*